---

- name: Install libselinux-python
  yum:
    name: libselinux-python
    state: present
  when:
    - ansible_selinux is defined
    - "'status' in ansible_selinux"
    - ansible_selinux.status == 'enabled'

- name: Install unbound
  yum:
    name: unbound
    state: present
