---
# tasks file for ansible-role-unbound

- include_vars: "{{ ansible_os_family }}.yml"

- set_fact:
    unbound_flags_merged: "{{ unbound_flags_default | combine(unbound_flags) }}"

- name: Include fact-{{ ansible_os_family }}.yml
  include_tasks: "fact-{{ ansible_os_family }}.yml"

- name: Assert register_unbound_version is defined
  assert:
    that:
      - register_unbound_version is defined
    msg: |
      [BUG] register_unbound_version must be defined by
      fact-{{ ansible_os_family }}.yml, but register_unbound_version is not
      defined. This means the role has a bug in it.

- set_fact:
    unbound_version: "{{ register_unbound_version.stdout }}"

- name: Assert unbound_version is in the expected format
  assert:
    that:
      - unbound_version | match('^\d+\.\d+\.\d+$')
    msg: |
      [BUG] unbound_version does not match expected version pattern.
      This means the role has a bug in it.

- name: Include install-{{ ansible_os_family }}.yml
  include_tasks: "install-{{ ansible_os_family }}.yml"

- name: Include x509.yml if unbound_include_role_x509_certificate
  import_tasks: "x509.yml"
  when:
    - unbound_include_role_x509_certificate

- name: Include "configure-{{ ansible_os_family }}.yml"
  include_tasks: "configure-{{ ansible_os_family }}.yml"

- name: Create unbound_script_dir
  file:
    path: "{{ unbound_script_dir }}"
    state: directory

- name: Create ansible-unbound-checkconf
  copy:
    dest: "{{ unbound_script_dir }}/ansible-unbound-checkconf"
    src: ansible-unbound-checkconf.sh
    mode: 0755

- name: Make unbound_conf_dir writable by unbound_user
  file:
    path: "{{ unbound_conf_dir }}"
    mode: 0775
    owner: root
    group: "{{ unbound_group }}"

- name: Create key files
  command: "unbound-control-setup -d {{ unbound_conf_dir }}"
  args:
    creates: "{{ unbound_config_server_key_file }}"

  # to validate unbound.conf(5), keys must be there even if you do not use them
  # (control-use-cert: no) because:
  #
  # * control-enable is set to "yes", control-use-cert is set to "no"
  # * (server|control)-(key|cert)-file are not specified because you would not
  #   use them
  # * unbound-checkconf validates the file, but it sets default values for
  #   missing configs, in this case, (server|control)-(key|cert)-file
  # * unbound-checkconf fails because the files are not there
  become_user: "{{ unbound_user }}"
  vars:

    # fix "Failed to set permissions on the temporary files Ansible needs to
    # create when becoming an unprivileged user" in ansible 2.1
    #
    # https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user
    ansible_ssh_pipelining: true

- name: Do chgrp unbound_group all keys
  file:
    mode: 0640
    owner: root
    group: "{{ unbound_group }}"
    path: "{{ item }}"
  with_items:
    - "{{ unbound_config_server_key_file }}"
    - "{{ unbound_config_server_cert_file }}"
    - "{{ unbound_config_control_key_file }}"
    - "{{ unbound_config_control_cert_file }}"

- name: Create unbound.conf
  template:
    src: unbound.conf.j2
    dest: "{{ unbound_conf_file }}"
    validate: "ansible-unbound-checkconf %s"
  notify: Restart unbound

- name: Start unbound
  service:
    name: "{{ unbound_service }}"
    state: started
